import { NextTamaguiProvider } from '../providers/NextTamaguiProvider';
import './global.css';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import { Toast } from '@shared/ui/components/universal/Toast';

export const metadata = {
  title: 'Welcome to Travel Booking',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  if (process.env.NODE_ENV === 'development') {
    return (
      <html lang="en" suppressHydrationWarning>
        <head>
          <script
            src="https://unpkg.com/react-scan/dist/auto.global.js"
            async
          />
        </head>
        <body>
          <NextTamaguiProvider>
            {children}
            <Toast />
          </NextTamaguiProvider>
        </body>
      </html>
    );
  }

  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <NextTamaguiProvider>
          {children}
          <Toast />
        </NextTamaguiProvider>
      </body>
    </html>
  );
}
